services:
  - type: web
    name: cbse-chatbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
